# 1.3 Задания

In [9]:
#1.3.1
import numpy as np

x = np.zeros((8,8), dtype = int)

x[1::2, ::2] = 1
x[::2, 1::2] = 1

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
#1.3.2
import numpy as np

x = np.zeros((5,5), dtype = int)

for i in range(0, 5, 1):
    x[i] = np.arange(0,5)

print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [22]:
#1.3.3
import numpy as np

x = np.random.random((3,3,3)) * 10//1

print(x)

[[[5. 6. 3.]
  [4. 0. 2.]
  [4. 3. 6.]]

 [[3. 2. 3.]
  [3. 8. 9.]
  [8. 1. 8.]]

 [[8. 7. 5.]
  [5. 3. 9.]
  [5. 3. 7.]]]


In [33]:
#1.3.4
import numpy as np

x = np.ones((5,5), dtype= int)

x[1:-1, 1:-1] = 0

print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [41]:
#1.3.5
import numpy as np

x = np.arange(0,10)
x = x[::-1]

print(x)

[9 8 7 6 5 4 3 2 1 0]


In [45]:
#1.3.6
import numpy as np

x = np.zeros((5,7), dtype = int)

print(x)
print("Форма матрицы: ")
print("Размер матрицы: ", x.shape)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Форма матрицы: 
Размер матрицы:  (5, 7)
