# 1.3 Задания

In [1]:
#1.3.1
import numpy as np

x = np.zeros((8,8), dtype = int)

x[1::2, ::2] = 1
x[::2, 1::2] = 1

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
#1.3.2
import numpy as np

x = np.zeros((5,5), dtype = int)

for i in range(0, 5, 1):
    x[i] = np.arange(0,5)

print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [3]:
#1.3.3
import numpy as np

x = np.random.random((3,3,3)) * 10//1

print(x)

[[[7. 5. 8.]
  [8. 2. 8.]
  [0. 5. 9.]]

 [[1. 2. 0.]
  [7. 6. 8.]
  [6. 9. 9.]]

 [[3. 3. 7.]
  [0. 9. 4.]
  [2. 1. 0.]]]


In [5]:
#1.3.4
import numpy as np

x = np.ones((7,7), dtype= int)

x[1:-1, 1:-1] = 0

print(x)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [6]:
#1.3.5
import numpy as np

x = np.arange(0,10)
x = x[::-1]

print(x)

[9 8 7 6 5 4 3 2 1 0]


In [11]:
#1.3.6
import numpy as np

x = np.array([[1, 2, 3, 11],
     [4, 5, 6, 12],
     [7 , 8, 9, 13]])
print(x)
print("Размер матрицы: ", x.shape)
print("Размерность матрицы", x.size)
print("Форма матрицы", x.ndim)

[[ 1  2  3 11]
 [ 4  5  6 12]
 [ 7  8  9 13]]
Размер матрицы:  (3, 4)
Размерность матрицы 12
Форма матрицы 2


In [ ]:
#2.3.1

import pandas as pd



In [13]:
#2.3.2

import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'

dataframe = pd.read_csv(url, on_bad_lines='skip')

dataframe.head(5)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K

In [14]:
#2.3.3

import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'

dataframe = pd.read_csv(url, on_bad_lines='skip')

dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

dataframe.iloc[2:5]

dataframe[dataframe['age'] <= 40].head(5)

age  workclass  education_num      marital_status         occupation  \
0   39  State-gov             13       Never-married       Adm-clerical   
2   38    Private              9            Divorced  Handlers-cleaners   
4   28    Private             13  Married-civ-spouse     Prof-specialty   
5   37    Private             14  Married-civ-spouse    Exec-managerial   
8   31    Private             14       Never-married     Prof-specialty   

    relationship   race  gender  hours_per_week native_country  capital  \
0  Not-in-family  White    Male              40  United-States     2174   
2  Not-in-family  White    Male              40  United-States        0   
4           Wife  Other  Female              40          Other        0   
5           Wife  White  Female              40  United-States        0   
8  Not-in-family  White  Female              50  United-States    14084   

  income_status  
0         <=50K  
2         <=50K  
4         <=50K  
5         <=50K  
8          >50K

In [ ]:
#3.3.2

import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

dataframe = pd.read_csv(url, on_bad_lines='skip')

