# 1.3 Задания

In [1]:
#1.3.1
import numpy as np

x = np.zeros((8,8), dtype = int)

x[1::2, ::2] = 1
x[::2, 1::2] = 1

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
#1.3.2
import numpy as np

x = np.zeros((5,5), dtype = int)

for i in range(0, 5, 1):
    x[i] = np.arange(0,5)

print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [3]:
#1.3.3
import numpy as np

x = np.random.random((3,3,3)) * 10//1

print(x)

[[[7. 5. 8.]
  [8. 2. 8.]
  [0. 5. 9.]]

 [[1. 2. 0.]
  [7. 6. 8.]
  [6. 9. 9.]]

 [[3. 3. 7.]
  [0. 9. 4.]
  [2. 1. 0.]]]


In [5]:
#1.3.4
import numpy as np

x = np.ones((7,7), dtype= int)

x[1:-1, 1:-1] = 0

print(x)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [6]:
#1.3.5
import numpy as np

x = np.arange(0,10)
x = x[::-1]

print(x)

[9 8 7 6 5 4 3 2 1 0]


In [10]:
#1.3.6
import numpy as np

x = np.array([[1, 2, 3, 11],
     [4, 5, 6, 12],
     [7 , 8, 9, 13]])
print(x)
print("Размер матрицы: ", x.shape)
print("Размерность матрицы", x.size)
print("Форма матрицы", x.ndim)

[[ 1  2  3 11]
 [ 4  5  6 12]
 [ 7  8  9 13]]
Размер матрицы:  (3, 4)
Размерность матрицы 12
Форма матрицы 2
